name: GitHub Pages

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./app

jobs:
  build:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: ./app/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Export
        run: npm run export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/out
          cname: ulab-uu.com
